### ISSUE TITLE
filtered view using specified labels for inclusion

### ISSUE THREAD

**Issue by monkeypants** [bugflow/kanned-bananas#27]
similar to #25, it would be great to filter the report to only show tickets with a certain label, e.g. `--filter-labels=project-foo,sustainment-bar`.

is it too much to include `project-*`? do we distinguish between "all of" labels vs. "any of"?

```
As a delivery manager responsible for a subset of tickets (indicated by labels)
I need a filtered summary based on the labels I'm responsible for
So that I can produce reports aligned to my sub-project or sub-budget
```

**Comment by dormerod** [comment]
@monkeypants, I think we can do this with an array of regex patterns. I have a branch where this is working:

- array elements for the included labels elements are always `and`
- array elements for the excluded list are always `or`
- if you really want to `or` included labels you can still roll your own with regex :wink:

**Comment by dormerod** [comment]
After sleeping on this, I might change it so that included and excluded labels both work in the same way (even if the above seems most logical to me).

**Comment by dormerod** [comment]
I decided to leave the functionality as described for now:

- array elements for the included labels are always `and`
- array elements for the excluded labels are always `or`
- if you really want to `or` included labels you can still roll your own with regex.

Mainly because I think you nearly always want to `or` excluded issues, and it's much easier to `or` than `and` in regular expressions (which solves the label inclusion problem for now).
